Repository openmv/openmv, pull requests merged in 2024-05, with the labels that each got.

#2191 modules/py_image: Update py_image_to with mp_arg_parse_all.
  scripts/examples/01-Camera/03-Event-Cameras/frogeye2020.py
  scripts/examples/01-Camera/03-Event-Cameras/frogeye2020_with_tracking.py
  scripts/examples/01-Camera/06-Time-of-Flight/tof_overlay.py
  scripts/examples/02-Image-Processing/01-Image-Filters/vflip_hmirror_transpose.py
  scripts/examples/08-RPC-Library/34-Remote-Control/image_transfer_jpg_as_the_remote_device_for_your_computer.py
  scripts/examples/08-RPC-Library/34-Remote-Control/image_transfer_jpg_streaming_as_the_remote_device_for_your_computer.py
  scripts/examples/08-RPC-Library/34-Remote-Control/popular_features_as_the_remote_device.py
  scripts/examples/09-WiFi/mjpeg_streamer.py
  scripts/examples/09-WiFi/mjpeg_streamer_ap.py
  scripts/examples/50-Arduino-Boards/Giga-H7/50-Board-Control/usb_vcp.py
  scripts/examples/50-Arduino-Boards/Nicla-Vision/50-Board-Control/usb_vcp.py
  scripts/examples/50-Arduino-Boards/Portenta-H7/50-Board-Control/usb_vcp.py
  scripts/examples/50-OpenMV-Boards/50-STM32-Boards/50-Board-Control/usb_vcp.py
  scripts/examples/50-OpenMV-Boards/60-Shields/62-Thermopile-Shield/thermal_overlay.py
  scripts/examples/50-OpenMV-Boards/60-Shields/62-Thermopile-Shield/thermal_overlay_lcd.py
  src/omv/imlib/draw.c
  src/omv/modules/py_image.c
Labels: enhancement

#2213 modules/py_image: Fix morph spelling.
  src/omv/modules/py_image.c
Labels: cleanup

#2208 imlib/draw: Cleanup drawline code.
  src/omv/imlib/draw.c
Labels: cleanup

#2215 modules/py_image: Move ksize to be pos_arg.
  src/omv/modules/py_image.c
Labels: bug

#2212 imlib/binary: Fix erode mask check.
  src/omv/imlib/binary.c
Labels: bug

#2210 imlib/pool: Remove obsolete pooling functions.
  scripts/examples/01-Camera/02-Optical-Flow/absolute-rotation-scale.py
  scripts/examples/01-Camera/02-Optical-Flow/absolute-translation.py
  scripts/examples/01-Camera/02-Optical-Flow/differential-rotation-scale.py
  scripts/examples/01-Camera/02-Optical-Flow/differential-translation.py
  scripts/examples/01-Camera/02-Optical-Flow/image-patches-absolute-rotation-scale.py
  scripts/examples/01-Camera/02-Optical-Flow/image-patches-absolute-translation.py
  scripts/examples/01-Camera/02-Optical-Flow/image-patches-differential-rotation-scale.py
  scripts/examples/01-Camera/02-Optical-Flow/image-patches-differential-translation.py
  scripts/examples/02-Image-Processing/00-Drawing/image_drawing.py
  scripts/examples/02-Image-Processing/00-Drawing/image_drawing_advanced.py
  src/omv/Makefile
  src/omv/boards/ARDUINO_GIGA/imlib_config.h
  src/omv/boards/ARDUINO_NANO_33_BLE_SENSE/imlib_config.h
  src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/imlib_config.h
  src/omv/boards/ARDUINO_NICLA_VISION/imlib_config.h
  src/omv/boards/ARDUINO_PORTENTA_H7/imlib_config.h
  src/omv/boards/OPENMV2/imlib_config.h
  src/omv/boards/OPENMV3/imlib_config.h
  src/omv/boards/OPENMV4/imlib_config.h
  src/omv/boards/OPENMV4P/imlib_config.h
  src/omv/boards/OPENMV4_PRO/imlib_config.h
  src/omv/boards/OPENMVPT/imlib_config.h
  src/omv/boards/OPENMV_RT1060/imlib_config.h
  src/omv/boards/PICO/imlib_config.h
  src/omv/imlib/pool.c
  src/omv/modules/py_image.c
  src/omv/ports/mimxrt/omv_portconfig.mk
  src/omv/ports/nrf/omv_portconfig.mk
  src/omv/ports/rp2/omv_portconfig.cmake
  src/omv/ports/stm32/omv_portconfig.mk
Labels: cleanup

#2207 misc: Increase delay after reset/power-down.
  src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
  src/omv/common/sensor_utils.c
Labels: bug
