Repository openmv/openmv, pull requests merged in 2024-07, with the labels that each got.

#2209 imlib/draw: Add AA support for draw_circle.
  src/omv/imlib/draw.c
Labels: enhancement

#2206 examples/ServoShield: Change to SoftI2c for RT.
  scripts/examples/50-OpenMV-Boards/60-Shields/61-Servo-Shield/main.py
Labels: bug

#2283 ports/mimxrt: Fix I2C for the MLX90640 driver.
  src/drivers/mlx90640/src/MLX90640_I2C_Driver.c
  src/drivers/mlx90641/src/MLX90641_I2C_Driver.c
  src/omv/ports/mimxrt/omv_portconfig.h
  src/omv/ports/nrf/omv_portconfig.h
  src/omv/ports/stm32/omv_portconfig.h
Labels: bug

#2214 modules/py_image: Update morph() to use arg parse.
  src/omv/modules/py_image.c
Labels: enhancement

#2228 imlib/draw: Add missing speculative read invalidates.
  src/omv/imlib/draw.c
  src/omv/imlib/imlib.h
  src/omv/modules/py_tv.c
  src/omv/ports/stm32/jpeg.c
Labels: bug

#2281 scripts/libraries: Update rpc_spi_master to use the machine module.
  scripts/libraries/rpc.py
Labels: enhancement

#2325 imlib/jpegd: Fix for JPEG decoder boundary problem.
  src/omv/imlib/jpegd.c
Labels: bugfix

#2330 modules/py_sensor: Add missing PAG7920 enum.
  src/omv/modules/py_sensor.c
Labels: bug

#2328 imlib/draw: Refactor draw_image to support gpu offload.
  src/omv/boards/ARDUINO_GIGA/imlib_config.h
  src/omv/boards/ARDUINO_GIGA/omv_boardconfig.h
  src/omv/boards/ARDUINO_NANO_33_BLE_SENSE/imlib_config.h
  src/omv/boards/ARDUINO_NANO_RP2040_CONNECT/imlib_config.h
  src/omv/boards/ARDUINO_NICLA_VISION/imlib_config.h
  src/omv/boards/ARDUINO_NICLA_VISION/omv_boardconfig.h
  src/omv/boards/ARDUINO_PORTENTA_H7/imlib_config.h
  src/omv/boards/ARDUINO_PORTENTA_H7/omv_boardconfig.h
  src/omv/boards/OPENMV1/imlib_config.h
  src/omv/boards/OPENMV2/imlib_config.h
  src/omv/boards/OPENMV2/omv_boardconfig.h
  src/omv/boards/OPENMV3/imlib_config.h
  src/omv/boards/OPENMV3/omv_boardconfig.h
  src/omv/boards/OPENMV4/imlib_config.h
  src/omv/boards/OPENMV4/omv_boardconfig.h
  src/omv/boards/OPENMV4P/imlib_config.h
  src/omv/boards/OPENMV4P/omv_boardconfig.h
  src/omv/boards/OPENMV4_PRO/imlib_config.h
  src/omv/boards/OPENMV4_PRO/omv_boardconfig.h
  src/omv/boards/OPENMVPT/imlib_config.h
  src/omv/boards/OPENMVPT/omv_boardconfig.h
  src/omv/boards/PICO/imlib_config.h
  src/omv/common/omv_gpu.h
  src/omv/imlib/draw.c
  src/omv/imlib/imlib.c
  src/omv/imlib/imlib.h
  src/omv/ports/stm32/omv_gpu.c
  src/omv/ports/stm32/omv_portconfig.mk
Labels: enhancement, cleanup

#2332 modules/py_ml: print model address location too.
  src/omv/modules/py_ml.c
Labels: enhancement

#2189 modules/py_image: Update all lineops to use the draw_image backend.
  src/omv/imlib/binary.c
  src/omv/imlib/imlib.c
  src/omv/imlib/imlib.h
  src/omv/imlib/mathop.c
  src/omv/modules/py_image.c
Labels: enhancement

#2331 scripts/libraries: Add missing return in microspeech.listen().
  scripts/libraries/ml/ml/apps.py
Labels: bug

#2329 modules/py_ml: Add uint16 support to match ndarrays.
  src/lib/tflm/tflm_backend.cc
  src/omv/modules/py_ml.c
Labels: bug, enhancement
